version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/alexa-to-discord

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
      
hooks:
  ApplicationStop:
    - location: bin/stop.sh
      timeout: 30
      runas: ubuntu
      
  BeforeInstall:
    - location: bin/clean-instance.sh
      timeout: 10
      runas: ubuntu

  AfterInstall:
    - location: bin/install.sh
      timeout: 300
      runas: ubuntu
    - location: bin/install-pkgs.sh
      timeout: 1200
      runas: ubuntu
    - location: bin/download-statics.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: bin/app-start.sh
      timeout: 60
      runas: ubuntu
